image: java
services:
  - postgres
variables:
  POSTGRES_DB: ebean
  POSTGRES_USER: ebean
  POSTGRES_PASSWORD: ebean

stages:
  - build
  
build_and_test:
  stage: build
  script:
    - ./gradlew clean build --info -Penv=ci