sudo: required
language: java
services:
  - docker
jdk:
  - oraclejdk8
env:
  - EBEAN_VERSION="8.4.1"
  - EBEAN_VERSION="8.4.2"
  - EBEAN_VERSION="8.5.1"
  - EBEAN_VERSION="8.6.1"
  - EBEAN_VERSION="8.7.1"
  - EBEAN_VERSION="8.8.1"
  - EBEAN_VERSION="9.1.1"
  - EBEAN_VERSION="9.1.2"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - gradle/wrapper/

script:
  - ./gradlew check jacocoTestReport codeCoverageReport -PebeanVersion=$EBEAN_VERSION

after_success:
  - bash <(curl -s https://codecov.io/bash)